### ISSUE TITLE
Curious: Why?

### ISSUE THREAD

**Issue by jblaine** [smurawski/chef-zero-scheduled-task#10]
What problem is this provisioner solving? The README says nothing about why.

**Comment by bheuvel** [comment]
@jblaine see https://github.com/test-kitchen/test-kitchen/issues/655#issuecomment-114921207

**Comment by smurawski** [comment]
Honestly, it was created to allow me to install SQL server over test-kitchen.  WinRM has a host of challenges, since the Windows OS wasn't originally designed for remote command line management.  A number of APIs are unavailable (partially or wholly) and there is the whole second-hop issue (services in Windows are not allowed to pass along your credentials, so accessing things like network shares or apis that require your user account become more difficult unless the computer account has rights to the same resource).  

At some point, I need to make this a feature of the core chef-zero provisioner and remove the need for this gem completely.
