### ISSUE TITLE
Running scheduled task as local system

### ISSUE THREAD

**Issue by DavidMcGrathUnionStreet** [smurawski/chef-zero-scheduled-task#27]
Hi

I am trying to run the scheduled task as SYSTEM. My provisioner settings are as below.

`
provisioner:
  name: chef_zero_scheduled_task
  task_username: SYSTEM
  task_password: nil
`

When I converge the node I see that its using windows temp as per the log extract below

`[2016-03-23T14:27:22+00:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at C:/Windows/TEMP/kitchen, C:/Windows/TEMP/kitchen`

But I receive an error sating it can't find the cookbooks in my runlist. Checking windows temp I can see that no cookbooks have been copied to the cache.

If I switch back to using the default by removing the task_username and task_password from my .kitchen.yml I can see it using the admin's home directory and the cookbooks are copied to the cache as expected.

**Comment by smurawski** [comment]
@DavidMcGrathUnionStreet Thanks for the bug report.  As soon as this PR https://github.com/test-kitchen/test-kitchen/pull/1012 is implemented in test-kitchen, I'm going to deprecate this provisioner, so unless this is a major blocker, I'll probably close this out when the above PR is merged. 

I did ping Matt on that PR to see if running under System will be an option.  If it isn't, I may keep this around in some form to allow for that, but I'd like to see the feature in core test-kitchen and available to any provisioner/verifier rather than this limited case.

**Comment by DavidMcGrathUnionStreet** [comment]
Hi Steve

Thanks for the response. Yes we have worked around the problem so please close the issue.
